-- Um pagamento, no maximo um credito.
--
-- O codigo ja era de uso unico — `codigos.usado_em` com a guarda
-- `and usado_em is null` no proprio UPDATE — e o reenvio do Ko-fi ja
-- batia no `kofi_message_id` UNIQUE. Mas faltava a restricao do outro
-- lado: nada impedia que o MESMO pagamento desse origem a dois creditos.
--
-- Hoje nenhum caminho o faz. O `assentar_pagamento` insere um credito e
-- so no ramo em que o pagamento acabou de ser criado. O problema e o
-- caminho que ainda nao existe: a vista que resolve a fila manual
-- (SPEC.md §10.4). Quem a escrever vai fazer o obvio — "creditar este
-- pagamento da fila" — e o obvio, com um duplo clique ou uma repeticao,
-- credita duas vezes. A defesa nao pode ser a atencao de quem escreve
-- esse codigo.
--
-- E o mesmo argumento do §3.3 sobre o `kofi_message_id`: a garantia e a
-- restricao, "do not rely on application-level checks alone".
--
-- Se um dia um pagamento tiver de pagar mais do que um acto — hoje nao
-- tem: a `codigos` nomeia um acto so, e uma compra com varios artigos vai
-- inteira para a fila — e esta restricao que tem de ser repensada, e nao
-- contornada com uma segunda linha de creditos.
alter table public.creditos
    add constraint creditos_um_por_pagamento unique (source_payment_id);
